// Random array generator code generated by ChatGPT

public class RandomArrayGenerator {

    public static int[] generateRandomArray(int size, int upperLimit) {
        int[] randomNumber = new int[size];
        for (int index = 0; index < size; index++) {
            randomNumber[index] = (int) Math.floor(Math.random() * upperLimit);
        }
        return randomNumber;
    }
}